name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name: Build the Docker image
      run: docker build . --file slackware-gcc/Dockerfile --tag $DOCKER_USER/$REPO_NAME:15.0 # --tag slackware-gcc:$(date +%s)

    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:15.0
