name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file slackware-gcc/Dockerfile --tag slackware-gcc:$(date +%s)
      run: docker build . --file slackware-git/Dockerfile --tag slackware-git:$(date +%s)

