name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_VERSION: ${{secrets.REPO_VERSION}}

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: slackware-gcc
          - name: slackware-git
          - name: slackware-omnibus
          - name: slackware-sbopkg
          - name: slackware-jdk
          - name: slackware-multilib
          - name: slackware-steam
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name: Build the Docker image
      run: docker build . --file ${{ matrix.name }}/Dockerfile --tag $DOCKER_USER/${{ matrix.name }}:$REPO_VERSION # --tag slackware-gcc:$(date +%s)

    - name: Docker Push
      run: docker push $DOCKER_USER/${{ matrix.name }}:$REPO_VERSION
